code --install-extension vscjava.vscode-java-pack
code --install-extension pivotal.vscode-boot-dev-pack
code --install-extension redhat.vscode-xml
code --install-extension dcortes92.freemarker
code --install-extension sodatea.velocity
code --install-extension eamodio.gitlens
code --install-extension asciidoctor.asciidocvscode
code --install-extension humao.rest-client
code --install-extension redhat.fabric8-analytics
